apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-ui
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Louizy20/secure-image-build-t13.git  # <-- CHANGE to your repo URL
    targetRevision: main
    path: k8s/platform-ui-ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
